version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend-simple
    container_name: imena-gest-backend-simple
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-imena-gest-secret-2024}
      - DB_PATH=/data/database.sqlite
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173,http://localhost:8080}
    volumes:
      # Persistance de la base de données
      - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend (optionnel - si vous voulez tout déployer ensemble)
  frontend:
    image: nginx:alpine
    container_name: imena-gest-frontend
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./App.tsx:/usr/share/nginx/html/App.tsx:ro
      - ./index.tsx:/usr/share/nginx/html/index.tsx:ro
      - ./styles:/usr/share/nginx/html/styles:ro
      - ./components:/usr/share/nginx/html/components:ro
      - ./services:/usr/share/nginx/html/services:ro
      - ./utils:/usr/share/nginx/html/utils:ro
      - ./nginx-simple.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data:
