[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://web-production-fa225.up.railway.app/api/v1"

[context.deploy-preview.environment]
  VITE_API_URL = "https://web-production-fa225.up.railway.app/api/v1"