services:
  # Backend API
  - type: web
    name: imena-backend
    env: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: node backend-simple.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: imena_gest_super_secret_2024_medical_app
      - key: DB_TYPE
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: imena-db
          property: connectionString
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: imena-frontend
          property: host

  # Frontend
  - type: web
    name: imena-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: imena-backend
          property: host
        sync: false

# Base de données PostgreSQL
databases:
  - name: imena-db
    databaseName: imena_gest
    user: imena_user
