name: imena-gest
services:
- name: web
  source_dir: /
  github:
    repo: Frejustedev/IMENA-GEST-2
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: VITE_API_URL
    value: https://web-production-fa225.up.railway.app/api/v1
  - key: NODE_ENV
    value: production
