# ===========================================
# Configuration Prometheus pour IMENA-GEST
# Monitoring Production 24/7
# ===========================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'imena-gest-production'
    environment: 'production'

# Configuration des règles d'alertes
rule_files:
  - "rules/*.yml"

# Configuration Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Configuration des targets de scraping
scrape_configs:

  # ===== MONITORING PROMETHEUS =====
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # ===== MONITORING APPLICATION BACKEND =====
  - job_name: 'imena-backend'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'backend'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'nodejs_.*'
        target_label: service
        replacement: 'backend'

  # ===== MONITORING APPLICATION FRONTEND =====
  - job_name: 'imena-frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'frontend'

  # ===== MONITORING POSTGRESQL =====
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    params:
      collect[]:
        - 'pg_stat_database'
        - 'pg_stat_user_tables'
        - 'pg_stat_user_indexes'
        - 'pg_statio_user_tables'
        - 'pg_stat_activity'
        - 'pg_stat_replication'
        - 'pg_locks'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgresql'
      - target_label: service
        replacement: 'database'

  # ===== MONITORING REDIS =====
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'
      - target_label: service
        replacement: 'cache'

  # ===== MONITORING NGINX =====
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nginx'
      - target_label: service
        replacement: 'proxy'

  # ===== MONITORING SYSTÈME (NODE EXPORTER) =====
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'host-system'
      - target_label: service
        replacement: 'system'

  # ===== MONITORING DOCKER =====
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'docker-host'
      - target_label: service
        replacement: 'containers'

  # ===== MONITORING APPLICATIF CUSTOM =====
  - job_name: 'imena-metrics'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 15s
    metrics_path: /api/metrics
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'application'
      - target_label: service
        replacement: 'medical-app'

  # ===== MONITORING SSL CERTIFICATES =====
  - job_name: 'ssl-certificates'
    static_configs:
      - targets: ['ssl-exporter:9219']
    scrape_interval: 3600s  # Toutes les heures
    params:
      target: 
        - 'https://localhost:443'
        - 'https://imena-gest.com:443'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ssl-monitor'

  # ===== MONITORING BLACKBOX (EXTERNAL) =====
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://imena-gest.com
        - https://imena-gest.com/health
        - https://imena-gest.com/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - postgresql:5432
        - redis:6379
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Configuration stockage
storage:
  tsdb:
    path: /prometheus
    retention.time: 15d
    retention.size: 10GB
    wal-compression: true

# Configuration des features expérimentales
feature_flags:
  - promql-at-modifier
  - promql-negative-offset
